basicjune/config/routes.rb
Rails.application.routes.draw do




  	get 'plots', to:'plots#index'
  	post 'plots', to:'plots#create'
  	get 'plots/new', to:'plots#new', as: :new_plot
  	get 'plots/:id/edit', to:'plots#edit', as: :edit_plot
  	# get 'plots/:id', to:'plots#show', as: :plot
  	patch 'plots/:id', to:'plots#update'
  	delete 'plots/:id', to:'plots#destroy' ,as: :delete_plot



  	get 'plots/sign_in', to:'plots#sign_in'
  	post 'plots/create_session', to:'plots#create_session'





	get 'users/:id/edit', to: 'users#edit'
	patch 'users/:id', to: 'users#update', as: :user
	get 'users', to:'users#index'
	get 'users/new', to:'users#new'
	post 'users', to:'users#create'
	
	get 'users/sign_in', to: 'users#sign_in'
	post 'users/create_session', to:'users#create_session'
	get 'users/sign_out', to:'users#sign_out'


	get 'examples', to:'examples#index'
	get 'examples/new', to:'examples#new'
	post 'examples',  to:'examples#create'
	get 'examples/:id/edit', to:'examples#edit', as: :example_new
	patch 'examples/:id', to:'examples#update', as: :example
	#get 'examples/:id/delete', to:'examples#delete', as: :example_new1
	delete 'examples/:id' , to: 'examples#delete', as: :destroy_post

	get 'examples/sign_in', to: 'examples#sign_in'
	post 'examples/create_session', to:'examples#create_session' 
	get 'examples/sign_out', to:'examples#sign_out'




  
  get 'posts/new', to: 'posts#new'
  get 'posts', to: 'posts#index'
  post 'posts', to: 'posts#create'

  get 'users/users_list'

	# get <url>, to '<controller_name>#<action_name>'
  	get 'hello_rails', to: 'application#hello_rails'

  	# get 'users_list', to: 'users#users_list'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root 'posts#index'

end

basicjune/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

basicjune/app/models/comment.rb
class Comment < ApplicationRecord
end

basicjune/app/models/example.rb
class Example < ApplicationRecord
end

basicjune/app/models/plot.rb
class Plot < ApplicationRecord
end

basicjune/app/models/post.rb
class Post < ApplicationRecord
	 # belongs_to :User
end

basicjune/app/models/user.rb
class User < ApplicationRecord
	# has_many :posts
end

basicjune/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	skip_before_action :verify_authenticity_token

	def hello_rails
		
		html_output = "<html><head></head><body><p>Hello Python</p></body></html>"

		render html: html_output.html_safe
	end



end
 

basicjune/app/controllers/basic_controller.rb
class BasicController < ApplicationController

	def basic_list

	end

end

basicjune/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def comments_list

		@a = [1,2,3,4,5,]

	end
end

basicjune/app/controllers/examples_controller.rb
class ExamplesController < ApplicationController

  before_action :set_example, only: [:edit, :update, :delete]

  

  def index

  	@example = Example.all
    # @abc = Example.last.id
      if session[:example_id]
        @abc = Example.find(session[:example_id])
      end

  end


  def new

  	@example = Example.new


  end


  def create

  	Example.create(
      example_params

  		)
  	redirect_to action: 'index'


  end

  def edit

  		

  end

  def update
  		
  		
  		@example.update(
       example_params

  			)
  		redirect_to action:'index'



  end

  def delete
      

      @example.destroy

      redirect_to action: 'index'

  end


  def example_params
    params.require(:example).permit(:name, :designation, :password)

  end
  
  def create_session
     
     u = Example.find_by(designation: params[:designation], password: params[:password])
      session[:example_id]= u.id
     redirect_to action: 'index'


  end

  def sign_in



  end

  def sign_out

    if !session[:example_id].blank?
      session.delete(:example_id)
    end
    redirect_to action: 'index'

  end



   private
  def set_example
  
  @example = Example.find(params[:id])  

  end


end

  

basicjune/app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  # before_action :set_plot, only: [:show, :edit, :update, :destroy]

  # GET /plots
  # GET /plots.json
  def index
    if session[:plot_id]
      @xyz = Plot.find(session[:plot_id])
    end

    @plots = Plot.all
   
  end
    def sign_in

    end

    def create_sessiom

     u = Plot.find_by(comment: params[:comment])

     session[:plot_id]=u.id
     redirect_to action: 'index'

    end

  # GET /plots/1
  # GET /plots/1.json
  def show
    @plot = Plot.find(params[:id])
  end

  # GET /plots/new
  def new
    @plot = Plot.new
  end

  # GET /plots/1/edit
  def edit
    @plot = Plot.find(params[:id])
  end

  # POST /plots
  # POST /plots.json
  def create
   
    @plot = Plot.new(content: params[:plot][:content])

    respond_to do |format|
      if @plot.save
        format.html { redirect_to @plot, notice: 'Plot was successfully created.' }
        format.json { render :show, status: :created, location: @plot }
      else
        format.html { render :new }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plots/1
  # PATCH/PUT /plots/1.json
  def update
    @plot = Plot.find(params[:id])
    respond_to do |format|
      if @plot.update(plot_params)
        format.html { redirect_to @plot, notice: 'Plot was successfully updated.' }
        format.json { render :show, status: :ok, location: @plot }
      else
        format.html { render :edit }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plots/1
  # DELETE /plots/1.json
    def destroy
      @plot = Plot.find(params[:id])
    @plot.destroy
    respond_to do |format|
      format.html { redirect_to plots_url, notice: 'Plot was successfully destroyed.' }
      format.json { head :no_content }
    end

   

    # private
    # # Use callbacks to share common setup or constraints between actions.
    # def set_plot
    #   @plot = Plot.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plot_params
      params.require(:plot).permit(:content)
    end
  end
end

basicjune/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index

  	@posts = Post.all
  end


  def new

  end

  def create

  	
  	new_post = Post.create(title: params[:title], content: params[:content])

  	redirect_to action: 'index'
  end


  # def something_else
  # 	render 
  # end
end

basicjune/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index

		# @my_variable="somennjn sdcds"
		@a = User.all
		if session[:user_id]
		@signed_in_user = User.find(session[:user_id])
		end

	end

	

	def new

		@user = User.new
	end

	def create


		User.create(user_params)
		redirect_to action: 'index'

	end

	def edit
		
		@user = User.find(params[:id])


	end

		def update

		@user = User.find(params[:id])	
		@user.update(
user_params)
		redirect_to action: 'index'
		end

		def user_params 

			params.require(:user).permit(:name, :age, :email)
		end

		def sign_in
			


		end

		def create_session
				
			u = User.find_by(email: params[:email], password: params[:password])

			if(u.blank?)
			redirect_to action: 'sign_in'
			end
			session[:user_id] = u.id
			redirect_to action: 'index'
			

		end

		def sign_out

			if !session[:user_id].blank?
				session.delete(:user_id)
			end

			redirect_to action: 'index'
		end
	end

		

basicjune/app/helpers/application_helper.rb
module ApplicationHelper
end

basicjune/app/helpers/examples_helper.rb
module ExamplesHelper
end

basicjune/app/helpers/plots_helper.rb
module PlotsHelper
end

basicjune/app/helpers/posts_helper.rb
module PostsHelper
end

basicjune/app/views/basic/basic_list.html.erb
<% for i in 0..5%>
<%=i%>
<%end%>

basicjune/app/views/comments/comments_list.html.erb
<h1> To display array in the list</h1>

<ul>
	<% for i in 0..4 %>

	<li> <%= @a[i]%></li>
	<% end %>

</ul>

basicjune/app/views/examples/edit.html.erb
<h1>Edit form</h1>

<%= form_for @example do |f| %>

	<%= f.label :Name %>
	<%= f.text_field :name%>

	<br>

	<%= f.label :Desgination %>
	<%= f.text_field :designation%>

	<br>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<br>


	<%= f.submit %>

	<% end%>

basicjune/app/views/examples/index.html.erb
<h1>Examples#abc</h1>
<p>Find me in app/views/examples/abc.html.erb</p>

<% if @abc %>
<%=@abc.name %>
<p> You are signed in..!!! </p>

<%= link_to 'Sign-out', '/examples/sign_out' %>
<br>
<% end %>

<% @example.reverse.each do |p| %>
<br>
	<%= p.name %>--
	<%= p.designation %>
	
	<li><%= link_to 'Edit', example_new_path(p.id) %></li>
	<li><%=link_to "Delete",destroy_post_path(p), method: :delete%>
	<%end%>
	<br>
<!-- <p>Link to New form page is </p> -->
<br>

<%= link_to 'Sign-up', '/examples/new' %>
<br>
<br>
<%= link_to 'Sign-in', '/examples/sign_in' %>




	
	

basicjune/app/views/examples/new.html.erb
<h1>Desgination Create and update</h1>

<%= form_for @example do |f| %>

	<%= f.label :Name %>
	<%= f.text_field :name%>

	<br>

	<%= f.label :Desgination %>
	<%= f.text_field :designation%>

	<br>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<br>


	<%= f.submit %>

	<% end%>

basicjune/app/views/examples/sign_in.html.erb
<h1>User sign in</h1>

<%= form_tag examples_create_session_path, method: :post do %>

	<%=label_tag :designation %>
	<%=text_field_tag :designation %>

	<br>

	<%=label_tag :password %>
	<%=password_field_tag :password %>

	<br>

	<%=submit_tag "Sign-in" %>
	<% end %>

basicjune/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basicjune</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if @signed_in_user %>
      <h4>  Welcome <%= @signed_in_user.email %>!</h4>
      <% end %>
    <%= yield %>
  </body>
</html>

basicjune/app/views/plots/_form.html.erb
<%= form_with(model: plot, local: true) do |form| %>
  <% if plot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plot.errors.count, "error") %> prohibited this plot from being saved:</h2>

      <ul>
      <% plot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

basicjune/app/views/plots/edit.html.erb
<h1>Editing Plot</h1>

<%= render 'form', plot: @plot %>


<%= link_to 'Back', plots_path %>

basicjune/app/views/plots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plots</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% if @xyz %>

  <%= @xyz %>
  <% end %>

    <% @plots.each do |plot| %>
      <tr>
        <td><%= plot.content %></td>
      
        <td><%= link_to 'Edit', edit_plot_path(plot) %></td>
        <td><%= link_to 'Destroy', delete_plot_path(plot), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plot', new_plot_path %>

basicjune/app/views/plots/new.html.erb
<h1>New Plot</h1>

<%= render 'form', plot: @plot %>

<%= link_to 'Back', plots_path %>

basicjune/app/views/plots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @plot.content %>
</p>

<%= link_to 'Edit', edit_plot_path(@plot) %> |
<%= link_to 'Back', plots_path %>

basicjune/app/views/plots/sign_in.html.erb
	<h1>User sign in</h1>

<%= form_tag examples_create_session_path, method: :post do %>

	<%=label_tag :Comment %>
	<%=text_field_tag :Comment %>

	<br>

	<%=submit_tag "Sign-in" %>
	<% end %>

basicjune/app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<ul>
<% @posts.reverse.each do |p| %>

<li>
	<h4><%= p.title %></h4>
	<p><%= p.content %></p>
</li>

<% end %>
</ul>

basicjune/app/views/posts/new.html.erb
<h1>Create New Post</h1>


<form action="/posts" method="post">

	<label for="title">Title</label>
	<input name="title" type="text" id="title">
	<br>

	<label for="content">Content</label>
	<textarea name="content" id="content"></textarea>

	<br>

	<input type="submit">


</form>

basicjune/app/views/users/edit.html.erb
<h1>Edit user profile</h1>




<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>

	<br>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<br>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<br>

	<%= f.label :age %>
	<%= f.number_field :age %>

	<br>

	<%= f.submit %>


	<% end %>

basicjune/app/views/users/index.erb
<h1> Inside users Controller > Users List </h1>



<% @a.reverse.each do |u| %>
	<%=u.name%>
	<br>
	<%end%>

basicjune/app/views/users/new.html.erb
<h1>User Sign up</h1>



<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>

	<br>

	

	<%= f.label :name %>
	<%= f.text_field :name %>

	<br>

	<%= f.label :age %>
	<%= f.number_field :age %>

	<br>

	<%= f.submit %>


	<% end %>

basicjune/app/views/users/sign_in.html.erb
<h1>USer Sign in</h1>

<%= form_tag users_create_session_path, method: :post do %>

	<%= label_tag :email %>
	<%= text_field_tag :email %>

	<br>

	<%= label_tag :password %>
	<%= password_field_tag :password %>

	<br>

	<%= submit_tag "Sign_in" %>
	<% end%>